### ISSUE TITLE
Suggestion: Change title color

### ISSUE THREAD

**Issue by donpedro-pomidores** [mrfreddie04/github-crash-course-#1]
I think it looks better the main title is a bit darker.
The styling rule could be changed like this:
```css
h1 {
  color: #d19937;
}
```
